export const SET_INVOICELIST = 'SET_INVOICELIST';
export const RESET_INVOICELIST = 'RESET_INVOICELIST';
export const SET_INVOICE = 'SET_INVOICE';
export default {
  SET_INVOICELIST,
  RESET_INVOICELIST,
  SET_INVOICE
};
